[project]
name = "ai-face-similarity-test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "deepface>=0.0.93",
    "flask>=3.1.1",
    "numpy<2",
]
